name: flutter_social_auth
description: Flutter package for login with social accounts like google, facebook, apple
version: 0.0.1
homepage: https://firebase.flutter.dev/docs/auth/social/

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^5.0.11
  google_sign_in: ^6.1.0
  http: ^0.13.6
  sign_in_with_apple: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
  - assets/icons/
